export enum ConnectType {
  CONNECT_WALLET = 'CONNECT_WALLET',
  CONNECT_TELEGRAM = 'CONNECT_TELEGRAM',
  CONNECT_GOOGLE = 'CONNECT_GOOGLE',
  CONNECT_TWITTER = 'CONNECT_TWITTER',
  CONNECT_EMAIL = 'CONNECT_EMAIL',
  CONNECT_FACEBOOK = 'CONNECT_FACEBOOK',
}
