/*
  Warnings:

  - The values [ERC721_PROXY,ERC1155_PROXY] on the enum `MULTICHAIN_CONTRACT_TYPE` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "MULTICHAIN_CONTRACT_TYPE_new" AS ENUM ('MARKETPLACE', 'NFT_PROXY', 'ERC20_PROXY');
ALTER TABLE "ContractMarketplace" ALTER COLUMN "contractType" TYPE "MULTICHAIN_CONTRACT_TYPE_new" USING ("contractType"::text::"MULTICHAIN_CONTRACT_TYPE_new");
ALTER TYPE "MULTICHAIN_CONTRACT_TYPE" RENAME TO "MULTICHAIN_CONTRACT_TYPE_old";
ALTER TYPE "MULTICHAIN_CONTRACT_TYPE_new" RENAME TO "MULTICHAIN_CONTRACT_TYPE";
DROP TYPE "MULTICHAIN_CONTRACT_TYPE_old";
COMMIT;
